name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token "${{ 1//0gkEpViyXYlZkCgYIARAAGBASNwF-L9IrlX3l0sUhVmDi3bAmti_otBeGEO5AYvAhBZLle0u-hMjJzpRhHzfvAORyIySMe090YHE }}"
